#
# Make a version file that includes the HPH version and git revision
#
SET(HPH_PACKAGE_NAME "hph")
SET(HPH_VERSION_MAJOR "0")
SET(HPH_VERSION_MINOR "1")
SET(HPH_VERSION_PATCH "beta")
SET(HPH_VERSION "${HPH_VERSION_MAJOR}.${HPH_VERSION_MINOR}.${HPH_VERSION_PATCH}")
EXECUTE_PROCESS(
    COMMAND git log -1 --format=%h
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

CONFIGURE_FILE(
    ${CMAKE_MODULE_PATH}/version.h.in
    ${CMAKE_SOURCE_DIR}/include/hph/version.h
)
