# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call('_hpHawkes_rcpp_hello', PACKAGE = 'hpHawkes')
}

#' Create HPH engine object
#'
#' Helper function creates HPH engine object with given latent dimension, location count and various
#' implementation details. Called by \code{hpHawkes::engineInitial()}.
#'
#' @param embeddingDimension Dimension of latent locations.
#' @param locationCount Number of locations and size of distance matrix.
#' @param tbb Number of CPU cores to be used.
#' @param simd For CPU implementation: no SIMD (\code{0}), SSE (\code{1}) or AVX (\code{2}).
#' @param gpu Which GPU to use? If only 1 available, use \code{gpu=1}. Defaults to \code{0}, no GPU.
#' @param single Set \code{single=1} if your GPU does not accommodate doubles.
#' @return HPH engine object.
#'
#' @export
createEngine <- function(embeddingDimension, locationCount, tbb, simd, gpu, single) {
    .Call('_hpHawkes_createEngine', PACKAGE = 'hpHawkes', embeddingDimension, locationCount, tbb, simd, gpu, single)
}

.setTimesData <- function(sexp, data) {
    invisible(.Call('_hpHawkes_setTimesData', PACKAGE = 'hpHawkes', sexp, data))
}

.setRandomRates <- function(sexp, randomRates) {
    invisible(.Call('_hpHawkes_setRandomRates', PACKAGE = 'hpHawkes', sexp, randomRates))
}

.setParameters <- function(sexp, parameters) {
    invisible(.Call('_hpHawkes_setParameters', PACKAGE = 'hpHawkes', sexp, parameters))
}

.getLogLikelihoodGradient <- function(sexp, len) {
    .Call('_hpHawkes_getLogLikelihoodGradient', PACKAGE = 'hpHawkes', sexp, len)
}

.getProbsSelfExcite <- function(sexp, len) {
    .Call('_hpHawkes_getProbsSelfExcite', PACKAGE = 'hpHawkes', sexp, len)
}

.getRandomRatesLogLikelihoodGradient <- function(sexp, len) {
    .Call('_hpHawkes_getRandomRatesLogLikelihoodGradient', PACKAGE = 'hpHawkes', sexp, len)
}

.updateLocations <- function(sexp, locations) {
    invisible(.Call('_hpHawkes_updateLocations', PACKAGE = 'hpHawkes', sexp, locations))
}

.getSumOfLikContribs <- function(sexp) {
    .Call('_hpHawkes_getSumOfLikContribs', PACKAGE = 'hpHawkes', sexp)
}

